#-------------------------------------------------------------------------------
# ESCREVER PARA CONVERTER LOCAL
SEP<-"#-------------------------------------------------------------------------------\n"
#-------------------------------------------------------------------------------
source("BSC.R")
source("HansenMultipoles.R")
#-------------------------------------------------------------------------------
# PARAMETROS DO FEIXE DE BESSEL
#-------------------------------------------------------------------------------
lambda=.5e-6
k=2*pi/lambda
n.lambda=10
NP=200
a<-5*lambda
b<-8*lambda
M<-7
N<-9
kx<-M*pi/a
ky<-N*pi/b
gama<-sqrt(kx^2+ky^2)
kz<-sqrt(k^2-gama^2)
dx<-a/(NP-1)
dy<-b/(NP-1)
x<-seq(0,a,by=dx)
y<-seq(0,b,by=dy)
z<-x
lmax<-as.integer(max(c(10,max(k*abs(x)),max(k*abs(y)))))
cat(SEP)
cat("LMAX=",lmax,"\n",sep="")
#-------------------------------------------------------------------------------
xo<-x[111]+dx/2
yo<-y[171]+dy/2
zo<-z[182]+dx/2
#-------------------------------------------------------------------------------
x<-x-xo
y<-y-yo
z<-z-zo
#-------------------------------------------------------------------------------
xe<-sample(x,1)
ye<-sample(y,1)
ze<-sample(z,1)
#-------------------------------------------------------------------------------
S<-1
P<-1
M<-4
#-------------------------------------------------------------------------------
Em<-((1+P)*psi.wg(gama,kz,xe+xo,ye+yo,ze+zo,(M-1),S)/2-P*((gama/k)^2)*psi.wg(gama,kz,xe+xo,ye+yo,ze+zo,(M-1)+S*(P-1),S)/2)
Ez<--1i*P*S*((gama/k)*(kz/k))*psi.wg(gama,kz,xe+xo,ye+yo,ze+zo,(M-1)+S*P,S)/sqrt(2)
Ep<-((1-P)*psi.wg(gama,kz,xe+xo,ye+yo,ze+zo,(M-1),S)/2+P*((gama/k)^2)*psi.wg(gama,kz,xe+xo,ye+yo,ze+zo,(M-1)+S*(P+1),S)/2)
#
Hm<--1i*P*(kz/k)*psi.wg(gama,kz,xe+xo,ye+yo,ze+zo,M-1,S)*(1+P)/2
Hz<--S*(gama/k)*psi.wg(gama,kz,xe+xo,ye+yo,ze+zo,(M-1)+S*P,S)/sqrt(2)
Hp<--1i*P*(kz/k)*psi.wg(gama,kz,xe+xo,ye+yo,ze+zo,M-1,S)*(1-P)/2
#-------------------------------------------------------------------------------
E<-c(Em,Ez,Ep)
H<-c(Hm,Hz,Hp)
cat(SEP)
print(cbind(E,H))
cat(SEP)
#-------------------------------------------------------------------------------
u<-BesselBeamP(gama,kz,xo,yo,zo,lmax,M,S,P)
v<-HansenMultipoles(k,xe,ye,ze,lmax)

Em.pwe<-sum(u$GTE*v$M.m-u$GTM*v$N.m)
Ez.pwe<-sum(u$GTE*v$M.z-u$GTM*v$N.z)
Ep.pwe<-sum(u$GTE*v$M.p-u$GTM*v$N.p)

Hm.pwe<-sum(u$GTM*v$M.m+u$GTE*v$N.m)
Hz.pwe<-sum(u$GTM*v$M.z+u$GTE*v$N.z)
Hp.pwe<-sum(u$GTM*v$M.p+u$GTE*v$N.p)
#-------------------------------------------------------------------------------
# CONFERINDO
#-------------------------------------------------------------------------------
E.pwe<-c(Em.pwe,Ez.pwe,Ep.pwe)
H.pwe<-c(Hm.pwe,Hz.pwe,Hp.pwe)
cat(SEP)
print(cbind(E.pwe,H.pwe))
cat(SEP)
#-------------------------------------------------------------------------------
# CALCULO EM LARGA ESCALA
#-------------------------------------------------------------------------------
LE<-FALSE
if(LE){
   source("LE-BBP.R")
}
#-------------------------------------------------------------------------------
# FIM
#-------------------------------------------------------------------------------
